// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppInfo():Promise<Record<string, string>>;

export function GetEmotion():Promise<string>;

export function Hide():Promise<void>;

export function LoadConfig():Promise<string>;

export function LoadInitSettings():Promise<string>;

export function Quit():Promise<void>;

export function ResetInitSettings():Promise<boolean>;

export function SaveConfig(arg1:string):Promise<boolean>;

export function SaveInitSettings(arg1:string):Promise<boolean>;

export function SetClickThrough(arg1:boolean):Promise<void>;

export function Show():Promise<void>;

export function StartDrag():Promise<void>;
