// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetEmotion() {
  return window['go']['main']['App']['GetEmotion']();
}

export function Hide() {
  return window['go']['main']['App']['Hide']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LoadInitSettings() {
  return window['go']['main']['App']['LoadInitSettings']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ResetInitSettings() {
  return window['go']['main']['App']['ResetInitSettings']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveInitSettings(arg1) {
  return window['go']['main']['App']['SaveInitSettings'](arg1);
}

export function SetClickThrough(arg1) {
  return window['go']['main']['App']['SetClickThrough'](arg1);
}

export function Show() {
  return window['go']['main']['App']['Show']();
}

export function StartDrag() {
  return window['go']['main']['App']['StartDrag']();
}
