// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Execute(arg1) {
  return window['go']['main']['tools']['Execute'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['tools']['SetContext'](arg1);
}
