// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['TTSManager']['GetConfig']();
}

export function IsSpeaking() {
  return window['go']['main']['TTSManager']['IsSpeaking']();
}

export function LoadConfig(arg1) {
  return window['go']['main']['TTSManager']['LoadConfig'](arg1);
}

export function PlayAudio(arg1, arg2) {
  return window['go']['main']['TTSManager']['PlayAudio'](arg1, arg2);
}

export function SetEmotion(arg1) {
  return window['go']['main']['TTSManager']['SetEmotion'](arg1);
}

export function SetEnabled(arg1) {
  return window['go']['main']['TTSManager']['SetEnabled'](arg1);
}

export function SetVolume(arg1) {
  return window['go']['main']['TTSManager']['SetVolume'](arg1);
}

export function Speak(arg1) {
  return window['go']['main']['TTSManager']['Speak'](arg1);
}

export function SpeakWithEmotion(arg1, arg2) {
  return window['go']['main']['TTSManager']['SpeakWithEmotion'](arg1, arg2);
}

export function Stop() {
  return window['go']['main']['TTSManager']['Stop']();
}
