// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig():Promise<string>;

export function IsSpeaking():Promise<boolean>;

export function LoadConfig(arg1:string):Promise<void>;

export function PlayAudio(arg1:string,arg2:string):Promise<void>;

export function SetEmotion(arg1:string):Promise<void>;

export function SetEnabled(arg1:boolean):Promise<void>;

export function SetVolume(arg1:number):Promise<void>;

export function Speak(arg1:string):Promise<void>;

export function SpeakWithEmotion(arg1:string,arg2:string):Promise<void>;

export function Stop():Promise<void>;
